# Auto draft：用于检查版本并在必要时新建一个 Draft

name: Auto draft

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup PHP environment
        uses: shivammathur/setup-php@2.8.0
        with:
          php-version: 7.2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check version
        id: check
        run: |
          cd tools
          result=$(php version-checker.php)
          if [ $? -ne 0 ]; then
            echo "::error::$result"
            exit 1
          fi
          echo "Current version: $result."
          ver="v$result"
          if ! git fetch --tags --quiet; then
            echo "::error::Cannot fetch tags."
            exit 1
          fi
          if [ $(git tag -l "$ver") ]; then
            echo "Tag $ver already exists. Skip."
            echo "::set-output name=continue::0"
            exit
          fi
          echo "This is a new version, drafting required."
          echo "::set-output name=continue::1"
          echo "::set-output name=tag::$ver"
          echo "::set-output name=title::CommentRuleset $result"
          if [[ $ver == *-* ]]; then
            echo "::set-output name=prerelease::1"
          else
            echo "::set-output name=prerelease::0"
          fi

      - name: Setup Node.js environment
        if: steps.check.outputs.continue == 1
        uses: actions/setup-node@v2.1.2

      - name: Build
        if: steps.check.outputs.continue == 1
        run: |
          pwd
          cd tools
          chmod +x build-frontend.sh
          ./build-frontend.sh
          cd ..
          cp Plugin.php tools/build
          cp Action.php tools/build
          cp LICENSE tools/build
          cp README.md tools/build
          cp -r libs tools/build
          cd tools/build
          zip -r CommentRuleset.zip *

      - name: Create draft
        if: steps.check.outputs.continue == 1
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          tag: ${{ steps.check.outputs.tag }}
          prerelease: ${{ steps.check.outputs.prerelease == 1 }}
          name: ${{ steps.check.outputs.title }}
          artifact: "CommentRuleset.zip"
          artifactErrorsFailBuild: true
