# Versioning：用于检查版本

name: Version check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup PHP environment
        uses: shivammathur/setup-php@2.8.0
        with:
          php-version: 7.2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check version
        run: |
          cd tools
          php version-checker.php
